### ISSUE TITLE
SSL Handshake error

### ISSUE THREAD

**Issue by puneetbharti** [cloudflare/nginx-google-oauth#16]
It is throwing an error while connecting to accounts.google.com 

lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/resty/http.lua:136: attempt to call method 'sslhandshake' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/resty/http.lua:136: in function 'ssl_handshake'
	/usr/local/share/lua/5.1/resty/http.lua:789: in function 'request_uri'
	/etc/nginx/auth/access.lua:105: in function 'request_access_token'
	/etc/nginx/auth/access.lua:203: in function 'authorize'

**Comment by bobrik** [comment]
Can you reproduce this error with `Dockerfile` from this repo? It seems like fault is in your openresty installation here.

**Comment by puneetbharti** [comment]
The problem is openresty is not able to pick up the CA certificate present on machine, we have to explicitly specify the path of certificate

**Comment by raymuncb** [comment]
Hi! What you do to explicitly specify the path of certificate? Thanks
