### ISSUE TITLE
Possible to use a Google Service Account?

### ISSUE THREAD

**Issue by fullofcaffeine** [cloudflare/nginx-google-oauth#21]
Hi!

I'd like to access the same app protected by google-oauth through `nginx-google-oauth` through the CLI/programatically. 

I'm wondering if I could use a Google Service Account (2-legged oauth) to access the protected app? 

I've searched around in the documentation (https://developers.google.com/identity/protocols/OAuth2ServiceAccount) and from what I understood, it's only meant to access Google APIs.

Thanks!

**Comment by bobrik** [comment]
This is not possible with `nginx-google-oauth`, but you can use any other authorization mechanism in nginx (IP restrictions, Basic Auth, etc) in combination. See docs for `satisfy` directive:

* http://nginx.org/en/docs/http/ngx_http_core_module.html#satisfy

**Comment by fullofcaffeine** [comment]
Ok, thanks!
