### ISSUE TITLE
Runtime Error : index upvalue 'domain' (a nil value)

### ISSUE THREAD

**Issue by sidey79** [cloudflare/nginx-google-oauth#37]
I've installed the loa module on my raspberry pi 1 which i'm using as a reverse proxy.

I've tried to protect one of my locations via the oauth2 module:

```
  location ~ ^/(ifttt|_oauth) {
      set $ngo_client_id         "123demo.apps.googleusercontent.com";
      set $ngo_client_secret     "secret";
      set $ngo_token_secret      "mysecret";
      set $ngo_secure_cookies    "true";
      set $ngo_http_only_cookies "true";
      access_by_lua_file "/etc/nginx/lua/access.lua";
  }
```
And added the resolver and ssl config for lua.

After getting the request in /_oauth i get a returncode 500 and this error in the errorlog:

```
error] 4207#4207: *4 lua entry thread aborted: runtime error: /etc/nginx/lua/access.lua:64: attempt to index upvalue 'domain' (a nil value)
stack traceback:
coroutine 0:
        /etc/nginx/lua/access.lua: in function 'check_domain'
        /etc/nginx/lua/access.lua:92: in function 'on_auth'
        /etc/nginx/lua/access.lua:234: in function 'authorize'
```

I've also tried to specify a domain, but same result.
`set $ngo_domainn           "gmail.com";`

Is this a config problem or a bug?

**Comment by bobrik** [comment]
```
set $ngo_domainn "gmail.com";
```

You have an extra `n` at the end of `ngo_domainn`. Fix that and it should work.

It is also possible to set it to an empty string to allow any domain.
