### ISSUE TITLE
/_oauth is a 403 error screen

### ISSUE THREAD

**Issue by samueljim** [cloudflare/nginx-google-oauth#51]
after a successful google login I am redirected back to my app where the page throws a 403 error

**Comment by samueljim** [comment]
2019/11/11 05:45:46 [error] 11159#11159: *308 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/access.lua:65: attempt to index upvalue 'domain' (a nil value) 

This error is being thrown when I add a resolver 8.8.8.8 to the config

**Comment by riking** [comment]
https://github.com/cloudflare/nginx-google-oauth/pull/52 should fix the "upvalue domain" error.
