### ISSUE TITLE
How to provide custom locations

### ISSUE THREAD

**Issue by maximehyh** [cloudflare/nginx-google-oauth#53]
Hello, 

I would like to provide custom location directives such as below but I do not understand how to provide them within the environment variable LOCATIONS. Would you have a small example? 

```
location / {
  proxy_pass http://node:3000/;
}
```

Thanks!

**Comment by quentindemetz** [comment]
Like this:
```
-e LOCATIONS="location / { proxy_pass http://node:3000; }"
```

**Comment by maximehyh** [comment]
Perfect thanks!
